title: Transformer-Based Sequential Recommender Systems
description: Tutorial materials for Transformer-Based Sequential Recommender Systems.
url: https://janmaltel.github.io
baseurl: /transformer-based-recsys-tutorial

markdown: kramdown

exclude:
  - README.md
